mysite/books/urls.py
# from django.contrib import admin
# from django.urls import path 
# from . import views

# urlpatterns = [
#     path('books/', views.index , name='index')
# ]
from django.urls import path
from django.conf.urls import url


from . import views
app_name = 'books'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('add', views.BookCreate.as_view(), name='book-add'),
    path('<int:pk>/update', views.BookUpdate.as_view(), name='book-update'),
    path('<int:pk>/delete', views.BookDelete.as_view(), name='book-delete'),


]


    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('addbook/', views.AddBook.as_view(), name='AddBook'),

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

mysite/addbooks/models.py
from django.db import models

# Create your models here.

mysite/books/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
	def get_absolute_url(self):
		return reverse('books:detail', kwargs = {'pk': self.pk})


	def __str__(self):
		return self.name + '-' + self.author


	name = models.CharField(max_length=100)
	author = models.CharField(max_length=100)
	price = models.CharField(max_length=100)
	type = models.CharField(max_length=100)
	book_image = models.CharField(max_length=1000)

mysite/addbooks/views.py
from django.shortcuts import render

# Create your views here.

mysite/books/views.py
from django.views import generic
from .models import Book
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy

app_name = 'book'

class IndexView(generic.ListView):
    template_name = 'books/index.html'
 
 
    def get_queryset(self):
        return Book.objects.all()
 
class BookCreate(CreateView):
    model = Book
    fields = ['name', 'author', 'price', 'type']

class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'author', 'price', 'type']


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books:index')


class DetailView(generic.DetailView):
    model = Book

    template_name = 'books/detail.html'

mysite/books/templates/books/base.html
{% load staticfiles %}
<head>
		<link rel="stylesheet" type="text/css" href="{% static 'book/style.css' %}">
  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>	
</head>
<html>
	<body>
			<nav class="navbar navbar-default">
  				<div class="container-fluid">
    				<div class="navbar-header">
     					<a class="navbar-brand" href="{% url 'books:index' %}">My Bookstore</a>
    				</div>
    				<ul class="nav navbar-nav">
      					<li><a href="#"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Books </a></li>
    				</ul>
     				<ul class="nav navbar-nav navbar-right">
      				   <li><a href="{% url 'books:book-add' %}"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Book </a></li>
      				   <li><a href="#"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout </a></li>
    				</ul>   				
  				</div>
			</nav>			
			{% block body %}
			{% endblock %}
	</body>
</html>

mysite/books/templates/books/book_form.html
{% extends 'books/base.html' %}
 
{% block body %}
 
    <div class="container-fluid">
   <div class="row">
      <div class="col-sm-12 col-md-7">
         <div class="panel panel-default">
            <div class="panel-body">
 
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-sucess">Submit</button>
                            </div>
                        </div>
                    </form>
 
 
            </div>
         </div>
      </div>
   </div>
</div>
 
{% endblock %}

mysite/books/templates/books/detail.html
{% extends 'books/base.html' %}
{% load staticfiles %}
{% block body %}
<head>
  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>	
</head>
<html>
	<body>
			<h2>Book Name: {{book.name}}</h2>
		<h3>Author: {{book.author}}</h3>
		<h3>Price: &#x20b9; {{book.price}}</h3>
		<h3>{{book.type}}</h3>
			
			<a href = "{% url 'books:book-update' book.id %}" class="btn btn-primary" type="submit" style="vertical-align:middle; background-color: clay"><span>Update</span></a> 
	</body>
</html>
{% endblock %}

mysite/books/templates/books/form-template.html
    {% for field in form %}
        <div class="submit-link-row">{{ field.label_tag }}&nbsp;&nbsp;{{ field }}</div>
        <br>
    {% endfor %}

mysite/books/templates/books/index.html
{% extends 'books/base.html' %}






{% block body %}
<link rel="stylesheet" type="text/css" href="books/style.css">
<div class=" col-md-10 jumbotron jumbotron-special" name="fig">
	<div class="col-md-12 span-2">
  <h2>Popular Books</h2>

  </div>
</div>

<ul>
	{% for book in object_list %}
	<div class="col-lg-3 col-md-4 col-sm-6 " >
  		<div class = "thumbnail">


    	  <div class = "caption">
      	   <h3>{{book.name}}</h3>
      	   <p>{{book.author}}</p>

      	   <p>
      	      <a href = "{% url 'books:detail' book.id %}" class = "btn btn-primary" role = "button">
      	         Details
     	       </a>

     	       <a href = "{% url 'books:book-delete' book.id %}" class = "btn btn-danger" role = "button">
     	          Delete
     	       </a>
         </p>
         </div>
      </div>


  	</div>
 {% endfor %}
</ul>
{% endblock %}